import {Out} from '@snickbit/out'
import {AppConfig} from './definitions'
import path from 'path'

export const DEFAULT_CONFIG_NAME = 'indexer.config.json'

export const posix = path.posix

export const indexer_banner = '// WARNING: This file is automatically generated. Any changes will be lost the next time the generator is run.'

export const $out = new Out('indexer')

export interface State {
	changed_files: string[]
	config: AppConfig
	configPath?: string
}

export const $state: State = {
	changed_files: [],
	config: {} as AppConfig
}

export function useState() {
	return $state
}
